# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with: 
        node-version: 12.x
     #Install dependencies
    - name: Install dependencies
      run: yarn
    
     #Execute build
    - name: Run build
      run: yarn build

    - name: Copy dist to digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"
     


 #Copy dist to digital ocean
 #Swap existing code in dist folder to new code
 #Execute yarn na Digital Ocean
 #Execute migrations do Typeorm
 #Restart node.js on server 
